version: '3'

services:
  nextjs-app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    mem_limit: 512M
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - MESSAGE_BROKER_URI=${MESSAGE_BROKER_URI}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
    command: npm run dev
    networks:
      - proxy_app-network

networks:
  proxy_app-network:
    external: true
