version: '3'

services:
  backend:
    container_name: profilytic-backend
    networks:
      - proxy_app-network
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 512M
    user: "1000:1000"
    ports:
      - "3005:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.development      

networks:
  proxy_app-network:
    external: true
