version: '3'

services:
  backend:
    container_name: profilytic-backend
    networks:
      - proxy_app-network
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 512M
    user: "1000:1000"
    ports:
      - "3005:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.development      
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - TEMPORAL_TASK_QUEUE=${TEMPORAL_TASK_QUEUE}
      - SENDPULSE_API_USER_ID=${SENDPULSE_API_USER_ID}
      - SENDPULSE_API_SECRET=${SENDPULSE_API_SECRET}
      - SENDPULSE_SENDER_EMAIL=${SENDPULSE_SENDER_EMAIL}
      - SENDPULSE_SENDER_NAME=${SENDPULSE_SENDER_NAME}
      - MONGODB_URI=${MONGODB_URI}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - DO_SPACES_KEY=${DO_SPACES_KEY}
      - DO_SPACES_SECRET=${DO_SPACES_SECRET}
      - DO_SPACES_ENDPOINT=${DO_SPACES_ENDPOINT}
      - DO_SPACES_BUCKET=${DO_SPACES_BUCKET}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
      - MESSAGE_BROKER_URI=${MESSAGE_BROKER_URI}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
    command: npm run dev

networks:
  proxy_app-network:
    external: true
