version: '3'

services:
  temporal-worker:
    networks:
      - proxy_app-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules # Ensure the container uses its own node_modules

    ports:
      - "3003:3000"
    mem_limit: 512M
    user: "1000:1000"
    env_file:
      - .env.development
  



networks:
  proxy_app-network:
    external: true
