name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ID_RSA }}

    - name: Add SSH key to known hosts
      run: ssh-keyscan profilytic.com >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: ssh -T -v -o StrictHostKeyChecking=no root@profilytic.com

    - name: Execute deployment script on server
      run: ssh -o StrictHostKeyChecking=no root@profilytic.com '/home/profilytic/DeployCommit.sh'
